services:
  - type: web
    name: portfolio-app
    env: dotnet
    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o ./publish
    startCommand: |
      cd publish
      dotnet Portfolio.dll
    envVars:
      - key: RENDER_ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_CLI_HOME
        value: /tmp/dotnet_home
    plan: free
    branch: main
    rootDir: .
    runtime: dotnet8.0
