services:
  - type: web
    name: portfolio-app
    env: dotnet
    buildCommand: dotnet restore && dotnet publish -c Release -o ./publish
    startCommand: cd publish && dotnet Portfolio.dll
    envVars:
      - key: RENDER_ASPNETCORE_ENVIRONMENT
        value: Production
    plan: free
    branch: main
    rootDir: .
