services:
  - type: web
    name: portfolio-app
    env: dotnet
    buildCommand: dotnet restore && dotnet publish -c Release -o ./publish
    startCommand: cd publish && dotnet Portfolio.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: free # eller standard beroende på dina behov
    branch: main # ändra till din huvudsakliga branch
    rootDir: .
